### PR TITLE
Issue/17 carthage ios support

### LINKED ISSUE #17: Minimum deployment target for iOS
I have added the library to my iOS project using Carthage, but Xcode says

````
Module file's minimum deployment target is ios11.4 v11.4
````

Is there a reason for that? The code looks like it should build and work also with older versions (my minimum is 10.0).

### PR DESCRIPTION
**Pull request by CutFlame**
Resolves #17 
Here's how to test/prove that it works:
1. In your Cartfile add this line:
`github "CutFlame/DictionaryCoding" "issue/17-carthage-ios-support"`

2. Then run a terminal in that same directory:
`carthage update --platform iOS --no-use-binaries`

should build successfully with minimum target of iOS 10.0

### CODE REVIEW

**Comment by drkibitz** [comment]
Just a polite ping to see if we can get this merged

**Comment by zaitsman** [comment]
@CutFlame hmm if i just add `github "elegantchaos/DictionaryCoding" == 1.0.6` in my Cartfile it works as is?

**Comment by zaitsman** [comment]
To answer my own question, the apps would work on iOS Simulator, but App Store submissions would fail. Raised a bug here: https://github.com/elegantchaos/DictionaryCoding/issues/22

**Comment by samdeane** [comment]
Sorry I missed the notification for this, somewhere along the way.

What were the actual modifications that prompted the `project.pbxproj` and `contents.xcworkspacedata` changes? Was it just Xcode rebuilding everything, or is there a real change there?

I'd prefer to put any settings changes into the xcconfig file if at all possible.

**Comment by CutFlame** [comment]
Yeah, the issue is solved in 1.0.6 so this change is no longer necessary. I will close the PR.

**Comment by zaitsman** [comment]
@samdeane would you mind checking this out though: https://github.com/elegantchaos/DictionaryCoding/issues/22

**Pull request closed without merging**
